version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: express-midas
      MYSQL_USER: user
      MYSQL_PASSWORD: password

    volumes:
      - mysql_dbdata:/var/lib/mysql
volumes:
  mysql_dbdata: